name: CI/CD Pipeline with Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar la caché de Cypress
      - name: Cache Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      # Paso 3: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Paso 4: Instalar dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # Paso 5: Instalar Cypress
      - name: Install Cypress
        run: npx cypress install

      # Paso 6: Iniciar el servidor
      - name: Start the server
        run: npm start &
      
      # Paso 7: Esperar a que el servidor esté listo
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:4321

      # Paso 8: Ejecutar pruebas de Cypress
      - name: Run Cypress Tests
        run: npx cypress run --headless --browser chrome

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    if: success()

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Paso 1: Obtener el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Construir el proyecto
      - name: Build project
        run: npm run build

      # Paso 5: Configurar GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Paso 6: Subir artefactos para GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Cambia 'dist' por la carpeta de tu build

      # Paso 7: Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
