name: CI/CD Pipeline with Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar la caché de Cypress
      - name: Cache Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      # Paso 3: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Paso 4: Instalar dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # Paso 5: Instalar Cypress
      - name: Install Cypress
        run: npx cypress install

      # Paso 6: Ejecutar pruebas de Cypress
      - name: Run Cypress Tests
        run: npx cypress run --headless --browser chrome
